// Generated by gencpp from file _object_recognition_msgs/ObjectRecognitionFeedback.msg
// DO NOT EDIT!


#ifndef _OBJECT_RECOGNITION_MSGS_MESSAGE_OBJECTRECOGNITIONFEEDBACK_H
#define _OBJECT_RECOGNITION_MSGS_MESSAGE_OBJECTRECOGNITIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace _object_recognition_msgs
{
template <class ContainerAllocator>
struct ObjectRecognitionFeedback_
{
  typedef ObjectRecognitionFeedback_<ContainerAllocator> Type;

  ObjectRecognitionFeedback_()
    {
    }
  ObjectRecognitionFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef std::shared_ptr< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectRecognitionFeedback_

typedef ::_object_recognition_msgs::ObjectRecognitionFeedback_<std::allocator<void> > ObjectRecognitionFeedback;

typedef std::shared_ptr< ::_object_recognition_msgs::ObjectRecognitionFeedback > ObjectRecognitionFeedbackPtr;
typedef std::shared_ptr< ::_object_recognition_msgs::ObjectRecognitionFeedback const> ObjectRecognitionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace _object_recognition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "_object_recognition_msgs/ObjectRecognitionFeedback";
  }

  static const char* value(const ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#no feedback\n"
"\n"
;
  }

  static const char* value(const ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectRecognitionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::_object_recognition_msgs::ObjectRecognitionFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_RECOGNITION_MSGS_MESSAGE_OBJECTRECOGNITIONFEEDBACK_H
