// Generated by gencpp from file _std_msgs/Time.msg
// DO NOT EDIT!


#ifndef _STD_MSGS_MESSAGE_TIME_H
#define _STD_MSGS_MESSAGE_TIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace _std_msgs
{
template <class ContainerAllocator>
struct Time_
{
  typedef Time_<ContainerAllocator> Type;

  Time_()
    : data()  {
    }
  Time_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
    }



   typedef ros::Time _data_type;
  _data_type data;





  typedef std::shared_ptr< ::_std_msgs::Time_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::_std_msgs::Time_<ContainerAllocator> const> ConstPtr;

}; // struct Time_

typedef ::_std_msgs::Time_<std::allocator<void> > Time;

typedef std::shared_ptr< ::_std_msgs::Time > TimePtr;
typedef std::shared_ptr< ::_std_msgs::Time const> TimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::_std_msgs::Time_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::_std_msgs::Time_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::_std_msgs::Time_<ContainerAllocator1> & lhs, const ::_std_msgs::Time_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::_std_msgs::Time_<ContainerAllocator1> & lhs, const ::_std_msgs::Time_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace _std_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::_std_msgs::Time_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::_std_msgs::Time_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_std_msgs::Time_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_std_msgs::Time_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_std_msgs::Time_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_std_msgs::Time_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::_std_msgs::Time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd7166c74c552c311fbcc2fe5a7bc289";
  }

  static const char* value(const ::_std_msgs::Time_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd7166c74c552c31ULL;
  static const uint64_t static_value2 = 0x1fbcc2fe5a7bc289ULL;
};

template<class ContainerAllocator>
struct DataType< ::_std_msgs::Time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "_std_msgs/Time";
  }

  static const char* value(const ::_std_msgs::Time_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::_std_msgs::Time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time data\n"
;
  }

  static const char* value(const ::_std_msgs::Time_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::_std_msgs::Time_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Time_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::_std_msgs::Time_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::_std_msgs::Time_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STD_MSGS_MESSAGE_TIME_H
