// Generated by gencpp from file _moveit_msgs/ChangeControlDimensions.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_CHANGECONTROLDIMENSIONS_H
#define _MOVEIT_MSGS_MESSAGE_CHANGECONTROLDIMENSIONS_H

#include <ros/service_traits.h>


#include <_moveit_msgs/ChangeControlDimensionsRequest.h>
#include <_moveit_msgs/ChangeControlDimensionsResponse.h>


namespace _moveit_msgs
{

struct ChangeControlDimensions
{

typedef ChangeControlDimensionsRequest Request;
typedef ChangeControlDimensionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeControlDimensions
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::ChangeControlDimensions > {
  static const char* value()
  {
    return "35b43a24f32e4654e4afa7596399fc3c";
  }

  static const char* value(const ::_moveit_msgs::ChangeControlDimensions&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::ChangeControlDimensions > {
  static const char* value()
  {
    return "_moveit_msgs/ChangeControlDimensions";
  }

  static const char* value(const ::_moveit_msgs::ChangeControlDimensions&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::ChangeControlDimensionsRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::ChangeControlDimensions >
template<>
struct MD5Sum< ::_moveit_msgs::ChangeControlDimensionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::ChangeControlDimensions >::value();
  }
  static const char* value(const ::_moveit_msgs::ChangeControlDimensionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::ChangeControlDimensionsRequest> should match
// service_traits::DataType< ::_moveit_msgs::ChangeControlDimensions >
template<>
struct DataType< ::_moveit_msgs::ChangeControlDimensionsRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::ChangeControlDimensions >::value();
  }
  static const char* value(const ::_moveit_msgs::ChangeControlDimensionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::ChangeControlDimensionsResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::ChangeControlDimensions >
template<>
struct MD5Sum< ::_moveit_msgs::ChangeControlDimensionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::ChangeControlDimensions >::value();
  }
  static const char* value(const ::_moveit_msgs::ChangeControlDimensionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::ChangeControlDimensionsResponse> should match
// service_traits::DataType< ::_moveit_msgs::ChangeControlDimensions >
template<>
struct DataType< ::_moveit_msgs::ChangeControlDimensionsResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::ChangeControlDimensions >::value();
  }
  static const char* value(const ::_moveit_msgs::ChangeControlDimensionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_CHANGECONTROLDIMENSIONS_H
