// Generated by gencpp from file _moveit_msgs/CheckIfRobotStateExistsInWarehouseResponse.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_CHECKIFROBOTSTATEEXISTSINWAREHOUSERESPONSE_H
#define _MOVEIT_MSGS_MESSAGE_CHECKIFROBOTSTATEEXISTSINWAREHOUSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace _moveit_msgs
{
template <class ContainerAllocator>
struct CheckIfRobotStateExistsInWarehouseResponse_
{
  typedef CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> Type;

  CheckIfRobotStateExistsInWarehouseResponse_()
    : exists(false)  {
    }
  CheckIfRobotStateExistsInWarehouseResponse_(const ContainerAllocator& _alloc)
    : exists(false)  {
  (void)_alloc;
    }



   typedef uint8_t _exists_type;
  _exists_type exists;





  typedef std::shared_ptr< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckIfRobotStateExistsInWarehouseResponse_

typedef ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<std::allocator<void> > CheckIfRobotStateExistsInWarehouseResponse;

typedef std::shared_ptr< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse > CheckIfRobotStateExistsInWarehouseResponsePtr;
typedef std::shared_ptr< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse const> CheckIfRobotStateExistsInWarehouseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator1> & lhs, const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.exists == rhs.exists;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator1> & lhs, const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace _moveit_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8c90de4adc1219c86af9c2874c0c1b5";
  }

  static const char* value(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8c90de4adc1219cULL;
  static const uint64_t static_value2 = 0x86af9c2874c0c1b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "_moveit_msgs/CheckIfRobotStateExistsInWarehouseResponse";
  }

  static const char* value(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool exists\n"
"\n"
;
  }

  static const char* value(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.exists);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckIfRobotStateExistsInWarehouseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse_<ContainerAllocator>& v)
  {
    s << indent << "exists: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.exists);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_CHECKIFROBOTSTATEEXISTSINWAREHOUSERESPONSE_H
