// Generated by gencpp from file _moveit_msgs/CheckIfRobotStateExistsInWarehouse.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_CHECKIFROBOTSTATEEXISTSINWAREHOUSE_H
#define _MOVEIT_MSGS_MESSAGE_CHECKIFROBOTSTATEEXISTSINWAREHOUSE_H

#include <ros/service_traits.h>


#include <_moveit_msgs/CheckIfRobotStateExistsInWarehouseRequest.h>
#include <_moveit_msgs/CheckIfRobotStateExistsInWarehouseResponse.h>


namespace _moveit_msgs
{

struct CheckIfRobotStateExistsInWarehouse
{

typedef CheckIfRobotStateExistsInWarehouseRequest Request;
typedef CheckIfRobotStateExistsInWarehouseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckIfRobotStateExistsInWarehouse
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse > {
  static const char* value()
  {
    return "3b47364b81dd44f643fa67c9cd127486";
  }

  static const char* value(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse > {
  static const char* value()
  {
    return "_moveit_msgs/CheckIfRobotStateExistsInWarehouse";
  }

  static const char* value(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse >
template<>
struct MD5Sum< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseRequest> should match
// service_traits::DataType< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse >
template<>
struct DataType< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse >
template<>
struct MD5Sum< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse> should match
// service_traits::DataType< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse >
template<>
struct DataType< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::CheckIfRobotStateExistsInWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::CheckIfRobotStateExistsInWarehouseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_CHECKIFROBOTSTATEEXISTSINWAREHOUSE_H
