// Generated by gencpp from file _moveit_msgs/DeleteRobotStateFromWarehouse.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_DELETEROBOTSTATEFROMWAREHOUSE_H
#define _MOVEIT_MSGS_MESSAGE_DELETEROBOTSTATEFROMWAREHOUSE_H

#include <ros/service_traits.h>


#include <_moveit_msgs/DeleteRobotStateFromWarehouseRequest.h>
#include <_moveit_msgs/DeleteRobotStateFromWarehouseResponse.h>


namespace _moveit_msgs
{

struct DeleteRobotStateFromWarehouse
{

typedef DeleteRobotStateFromWarehouseRequest Request;
typedef DeleteRobotStateFromWarehouseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DeleteRobotStateFromWarehouse
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::DeleteRobotStateFromWarehouse > {
  static const char* value()
  {
    return "dab44354403f811c40b84964e068219c";
  }

  static const char* value(const ::_moveit_msgs::DeleteRobotStateFromWarehouse&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::DeleteRobotStateFromWarehouse > {
  static const char* value()
  {
    return "_moveit_msgs/DeleteRobotStateFromWarehouse";
  }

  static const char* value(const ::_moveit_msgs::DeleteRobotStateFromWarehouse&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::DeleteRobotStateFromWarehouseRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::DeleteRobotStateFromWarehouse >
template<>
struct MD5Sum< ::_moveit_msgs::DeleteRobotStateFromWarehouseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::DeleteRobotStateFromWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::DeleteRobotStateFromWarehouseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::DeleteRobotStateFromWarehouseRequest> should match
// service_traits::DataType< ::_moveit_msgs::DeleteRobotStateFromWarehouse >
template<>
struct DataType< ::_moveit_msgs::DeleteRobotStateFromWarehouseRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::DeleteRobotStateFromWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::DeleteRobotStateFromWarehouseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::DeleteRobotStateFromWarehouseResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::DeleteRobotStateFromWarehouse >
template<>
struct MD5Sum< ::_moveit_msgs::DeleteRobotStateFromWarehouseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::DeleteRobotStateFromWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::DeleteRobotStateFromWarehouseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::DeleteRobotStateFromWarehouseResponse> should match
// service_traits::DataType< ::_moveit_msgs::DeleteRobotStateFromWarehouse >
template<>
struct DataType< ::_moveit_msgs::DeleteRobotStateFromWarehouseResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::DeleteRobotStateFromWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::DeleteRobotStateFromWarehouseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_DELETEROBOTSTATEFROMWAREHOUSE_H
