// Generated by gencpp from file _moveit_msgs/ExecuteKnownTrajectory.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_EXECUTEKNOWNTRAJECTORY_H
#define _MOVEIT_MSGS_MESSAGE_EXECUTEKNOWNTRAJECTORY_H

#include <ros/service_traits.h>


#include <_moveit_msgs/ExecuteKnownTrajectoryRequest.h>
#include <_moveit_msgs/ExecuteKnownTrajectoryResponse.h>


namespace _moveit_msgs
{

struct ExecuteKnownTrajectory
{

typedef ExecuteKnownTrajectoryRequest Request;
typedef ExecuteKnownTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteKnownTrajectory
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::ExecuteKnownTrajectory > {
  static const char* value()
  {
    return "90682c5b72fe34a7ac8538ce473e228b";
  }

  static const char* value(const ::_moveit_msgs::ExecuteKnownTrajectory&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::ExecuteKnownTrajectory > {
  static const char* value()
  {
    return "_moveit_msgs/ExecuteKnownTrajectory";
  }

  static const char* value(const ::_moveit_msgs::ExecuteKnownTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::ExecuteKnownTrajectoryRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::ExecuteKnownTrajectory >
template<>
struct MD5Sum< ::_moveit_msgs::ExecuteKnownTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::ExecuteKnownTrajectory >::value();
  }
  static const char* value(const ::_moveit_msgs::ExecuteKnownTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::ExecuteKnownTrajectoryRequest> should match
// service_traits::DataType< ::_moveit_msgs::ExecuteKnownTrajectory >
template<>
struct DataType< ::_moveit_msgs::ExecuteKnownTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::ExecuteKnownTrajectory >::value();
  }
  static const char* value(const ::_moveit_msgs::ExecuteKnownTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::ExecuteKnownTrajectoryResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::ExecuteKnownTrajectory >
template<>
struct MD5Sum< ::_moveit_msgs::ExecuteKnownTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::ExecuteKnownTrajectory >::value();
  }
  static const char* value(const ::_moveit_msgs::ExecuteKnownTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::ExecuteKnownTrajectoryResponse> should match
// service_traits::DataType< ::_moveit_msgs::ExecuteKnownTrajectory >
template<>
struct DataType< ::_moveit_msgs::ExecuteKnownTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::ExecuteKnownTrajectory >::value();
  }
  static const char* value(const ::_moveit_msgs::ExecuteKnownTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_EXECUTEKNOWNTRAJECTORY_H
