// Generated by gencpp from file _moveit_msgs/GetMotionSequence.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_GETMOTIONSEQUENCE_H
#define _MOVEIT_MSGS_MESSAGE_GETMOTIONSEQUENCE_H

#include <ros/service_traits.h>


#include <_moveit_msgs/GetMotionSequenceRequest.h>
#include <_moveit_msgs/GetMotionSequenceResponse.h>


namespace _moveit_msgs
{

struct GetMotionSequence
{

typedef GetMotionSequenceRequest Request;
typedef GetMotionSequenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMotionSequence
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::GetMotionSequence > {
  static const char* value()
  {
    return "f94589b40ccfbb6b16dda7fd233b2a28";
  }

  static const char* value(const ::_moveit_msgs::GetMotionSequence&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::GetMotionSequence > {
  static const char* value()
  {
    return "_moveit_msgs/GetMotionSequence";
  }

  static const char* value(const ::_moveit_msgs::GetMotionSequence&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::GetMotionSequenceRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetMotionSequence >
template<>
struct MD5Sum< ::_moveit_msgs::GetMotionSequenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetMotionSequence >::value();
  }
  static const char* value(const ::_moveit_msgs::GetMotionSequenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetMotionSequenceRequest> should match
// service_traits::DataType< ::_moveit_msgs::GetMotionSequence >
template<>
struct DataType< ::_moveit_msgs::GetMotionSequenceRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetMotionSequence >::value();
  }
  static const char* value(const ::_moveit_msgs::GetMotionSequenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::GetMotionSequenceResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetMotionSequence >
template<>
struct MD5Sum< ::_moveit_msgs::GetMotionSequenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetMotionSequence >::value();
  }
  static const char* value(const ::_moveit_msgs::GetMotionSequenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetMotionSequenceResponse> should match
// service_traits::DataType< ::_moveit_msgs::GetMotionSequence >
template<>
struct DataType< ::_moveit_msgs::GetMotionSequenceResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetMotionSequence >::value();
  }
  static const char* value(const ::_moveit_msgs::GetMotionSequenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_GETMOTIONSEQUENCE_H
