// Generated by gencpp from file _moveit_msgs/GetMotionPlan.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_GETMOTIONPLAN_H
#define _MOVEIT_MSGS_MESSAGE_GETMOTIONPLAN_H

#include <ros/service_traits.h>


#include <_moveit_msgs/GetMotionPlanRequest.h>
#include <_moveit_msgs/GetMotionPlanResponse.h>


namespace _moveit_msgs
{

struct GetMotionPlan
{

typedef GetMotionPlanRequest Request;
typedef GetMotionPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMotionPlan
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::GetMotionPlan > {
  static const char* value()
  {
    return "29c3c85c8a4c241f7588a9b4da235097";
  }

  static const char* value(const ::_moveit_msgs::GetMotionPlan&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::GetMotionPlan > {
  static const char* value()
  {
    return "_moveit_msgs/GetMotionPlan";
  }

  static const char* value(const ::_moveit_msgs::GetMotionPlan&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::GetMotionPlanRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetMotionPlan >
template<>
struct MD5Sum< ::_moveit_msgs::GetMotionPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetMotionPlan >::value();
  }
  static const char* value(const ::_moveit_msgs::GetMotionPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetMotionPlanRequest> should match
// service_traits::DataType< ::_moveit_msgs::GetMotionPlan >
template<>
struct DataType< ::_moveit_msgs::GetMotionPlanRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetMotionPlan >::value();
  }
  static const char* value(const ::_moveit_msgs::GetMotionPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::GetMotionPlanResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetMotionPlan >
template<>
struct MD5Sum< ::_moveit_msgs::GetMotionPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetMotionPlan >::value();
  }
  static const char* value(const ::_moveit_msgs::GetMotionPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetMotionPlanResponse> should match
// service_traits::DataType< ::_moveit_msgs::GetMotionPlan >
template<>
struct DataType< ::_moveit_msgs::GetMotionPlanResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetMotionPlan >::value();
  }
  static const char* value(const ::_moveit_msgs::GetMotionPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_GETMOTIONPLAN_H
