// Generated by gencpp from file _moveit_msgs/GetPlanningScene.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_GETPLANNINGSCENE_H
#define _MOVEIT_MSGS_MESSAGE_GETPLANNINGSCENE_H

#include <ros/service_traits.h>


#include <_moveit_msgs/GetPlanningSceneRequest.h>
#include <_moveit_msgs/GetPlanningSceneResponse.h>


namespace _moveit_msgs
{

struct GetPlanningScene
{

typedef GetPlanningSceneRequest Request;
typedef GetPlanningSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlanningScene
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::GetPlanningScene > {
  static const char* value()
  {
    return "65cf69d3e7a0342e16374024d4eeef65";
  }

  static const char* value(const ::_moveit_msgs::GetPlanningScene&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::GetPlanningScene > {
  static const char* value()
  {
    return "_moveit_msgs/GetPlanningScene";
  }

  static const char* value(const ::_moveit_msgs::GetPlanningScene&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::GetPlanningSceneRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetPlanningScene >
template<>
struct MD5Sum< ::_moveit_msgs::GetPlanningSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetPlanningScene >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPlanningSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetPlanningSceneRequest> should match
// service_traits::DataType< ::_moveit_msgs::GetPlanningScene >
template<>
struct DataType< ::_moveit_msgs::GetPlanningSceneRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetPlanningScene >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPlanningSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::GetPlanningSceneResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetPlanningScene >
template<>
struct MD5Sum< ::_moveit_msgs::GetPlanningSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetPlanningScene >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPlanningSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetPlanningSceneResponse> should match
// service_traits::DataType< ::_moveit_msgs::GetPlanningScene >
template<>
struct DataType< ::_moveit_msgs::GetPlanningSceneResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetPlanningScene >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPlanningSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_GETPLANNINGSCENE_H
