// Generated by gencpp from file _moveit_msgs/GetPositionFKResponse.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_GETPOSITIONFKRESPONSE_H
#define _MOVEIT_MSGS_MESSAGE_GETPOSITIONFKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <_geometry_msgs/PoseStamped.h>
#include <_moveit_msgs/MoveItErrorCodes.h>

namespace _moveit_msgs
{
template <class ContainerAllocator>
struct GetPositionFKResponse_
{
  typedef GetPositionFKResponse_<ContainerAllocator> Type;

  GetPositionFKResponse_()
    : pose_stamped()
    , fk_link_names()
    , error_code()  {
    }
  GetPositionFKResponse_(const ContainerAllocator& _alloc)
    : pose_stamped(_alloc)
    , fk_link_names(_alloc)
    , error_code(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::_geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::_geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _pose_stamped_type;
  _pose_stamped_type pose_stamped;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _fk_link_names_type;
  _fk_link_names_type fk_link_names;

   typedef  ::_moveit_msgs::MoveItErrorCodes_<ContainerAllocator>  _error_code_type;
  _error_code_type error_code;





  typedef std::shared_ptr< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPositionFKResponse_

typedef ::_moveit_msgs::GetPositionFKResponse_<std::allocator<void> > GetPositionFKResponse;

typedef std::shared_ptr< ::_moveit_msgs::GetPositionFKResponse > GetPositionFKResponsePtr;
typedef std::shared_ptr< ::_moveit_msgs::GetPositionFKResponse const> GetPositionFKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator1> & lhs, const ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pose_stamped == rhs.pose_stamped &&
    lhs.fk_link_names == rhs.fk_link_names &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator1> & lhs, const ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace _moveit_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d8c20528014017b172ce1f1d15ac982";
  }

  static const char* value(const ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d8c20528014017bULL;
  static const uint64_t static_value2 = 0x172ce1f1d15ac982ULL;
};

template<class ContainerAllocator>
struct DataType< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "_moveit_msgs/GetPositionFKResponse";
  }

  static const char* value(const ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The resultant vector of PoseStamped messages that contains the (stamped) poses of the requested links\n"
"_geometry_msgs/PoseStamped[] pose_stamped\n"
"\n"
"# The list of link names corresponding to the poses\n"
"string[] fk_link_names\n"
"\n"
"MoveItErrorCodes error_code\n"
"\n"
"\n"
"================================================================================\n"
"MSG: _geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: _std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: _geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: _geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: _geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: _moveit_msgs/MoveItErrorCodes\n"
"int32 val\n"
"\n"
"# overall behavior\n"
"int32 SUCCESS=1\n"
"int32 FAILURE=99999\n"
"\n"
"int32 PLANNING_FAILED=-1\n"
"int32 INVALID_MOTION_PLAN=-2\n"
"int32 MOTION_PLAN_INVALIDATED_BY_ENVIRONMENT_CHANGE=-3\n"
"int32 CONTROL_FAILED=-4\n"
"int32 UNABLE_TO_AQUIRE_SENSOR_DATA=-5\n"
"int32 TIMED_OUT=-6\n"
"int32 PREEMPTED=-7\n"
"\n"
"# planning & kinematics request errors\n"
"int32 START_STATE_IN_COLLISION=-10\n"
"int32 START_STATE_VIOLATES_PATH_CONSTRAINTS=-11\n"
"\n"
"int32 GOAL_IN_COLLISION=-12\n"
"int32 GOAL_VIOLATES_PATH_CONSTRAINTS=-13\n"
"int32 GOAL_CONSTRAINTS_VIOLATED=-14\n"
"\n"
"int32 INVALID_GROUP_NAME=-15\n"
"int32 INVALID_GOAL_CONSTRAINTS=-16\n"
"int32 INVALID_ROBOT_STATE=-17\n"
"int32 INVALID_LINK_NAME=-18\n"
"int32 INVALID_OBJECT_NAME=-19\n"
"\n"
"# system errors\n"
"int32 FRAME_TRANSFORM_FAILURE=-21\n"
"int32 COLLISION_CHECKING_UNAVAILABLE=-22\n"
"int32 ROBOT_STATE_STALE=-23\n"
"int32 SENSOR_INFO_STALE=-24\n"
"int32 COMMUNICATION_FAILURE=-25\n"
"\n"
"# kinematics errors\n"
"int32 NO_IK_SOLUTION=-31\n"
;
  }

  static const char* value(const ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_stamped);
      stream.next(m.fk_link_names);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPositionFKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::_moveit_msgs::GetPositionFKResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose_stamped[]" << std::endl;
    for (size_t i = 0; i < v.pose_stamped.size(); ++i)
    {
      s << indent << "  pose_stamped[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::_geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.pose_stamped[i]);
    }
    s << indent << "fk_link_names[]" << std::endl;
    for (size_t i = 0; i < v.fk_link_names.size(); ++i)
    {
      s << indent << "  fk_link_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fk_link_names[i]);
    }
    s << indent << "error_code: ";
    s << std::endl;
    Printer< ::_moveit_msgs::MoveItErrorCodes_<ContainerAllocator> >::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_GETPOSITIONFKRESPONSE_H
