// Generated by gencpp from file _moveit_msgs/GetPositionIK.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_GETPOSITIONIK_H
#define _MOVEIT_MSGS_MESSAGE_GETPOSITIONIK_H

#include <ros/service_traits.h>


#include <_moveit_msgs/GetPositionIKRequest.h>
#include <_moveit_msgs/GetPositionIKResponse.h>


namespace _moveit_msgs
{

struct GetPositionIK
{

typedef GetPositionIKRequest Request;
typedef GetPositionIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPositionIK
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::GetPositionIK > {
  static const char* value()
  {
    return "185001c352b2e96cb475d82048e9df9a";
  }

  static const char* value(const ::_moveit_msgs::GetPositionIK&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::GetPositionIK > {
  static const char* value()
  {
    return "_moveit_msgs/GetPositionIK";
  }

  static const char* value(const ::_moveit_msgs::GetPositionIK&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::GetPositionIKRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetPositionIK >
template<>
struct MD5Sum< ::_moveit_msgs::GetPositionIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetPositionIK >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPositionIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetPositionIKRequest> should match
// service_traits::DataType< ::_moveit_msgs::GetPositionIK >
template<>
struct DataType< ::_moveit_msgs::GetPositionIKRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetPositionIK >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPositionIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::GetPositionIKResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetPositionIK >
template<>
struct MD5Sum< ::_moveit_msgs::GetPositionIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetPositionIK >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPositionIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetPositionIKResponse> should match
// service_traits::DataType< ::_moveit_msgs::GetPositionIK >
template<>
struct DataType< ::_moveit_msgs::GetPositionIKResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetPositionIK >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPositionIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_GETPOSITIONIK_H
