// Generated by gencpp from file _moveit_msgs/GetPositionFK.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_GETPOSITIONFK_H
#define _MOVEIT_MSGS_MESSAGE_GETPOSITIONFK_H

#include <ros/service_traits.h>


#include <_moveit_msgs/GetPositionFKRequest.h>
#include <_moveit_msgs/GetPositionFKResponse.h>


namespace _moveit_msgs
{

struct GetPositionFK
{

typedef GetPositionFKRequest Request;
typedef GetPositionFKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPositionFK
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::GetPositionFK > {
  static const char* value()
  {
    return "7e5228d4c9e3511cf5071ecf43c502b8";
  }

  static const char* value(const ::_moveit_msgs::GetPositionFK&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::GetPositionFK > {
  static const char* value()
  {
    return "_moveit_msgs/GetPositionFK";
  }

  static const char* value(const ::_moveit_msgs::GetPositionFK&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::GetPositionFKRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetPositionFK >
template<>
struct MD5Sum< ::_moveit_msgs::GetPositionFKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetPositionFK >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPositionFKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetPositionFKRequest> should match
// service_traits::DataType< ::_moveit_msgs::GetPositionFK >
template<>
struct DataType< ::_moveit_msgs::GetPositionFKRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetPositionFK >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPositionFKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::GetPositionFKResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetPositionFK >
template<>
struct MD5Sum< ::_moveit_msgs::GetPositionFKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetPositionFK >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPositionFKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetPositionFKResponse> should match
// service_traits::DataType< ::_moveit_msgs::GetPositionFK >
template<>
struct DataType< ::_moveit_msgs::GetPositionFKResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetPositionFK >::value();
  }
  static const char* value(const ::_moveit_msgs::GetPositionFKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_GETPOSITIONFK_H
