// Generated by gencpp from file _moveit_msgs/GetPlannerParamsResponse.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_GETPLANNERPARAMSRESPONSE_H
#define _MOVEIT_MSGS_MESSAGE_GETPLANNERPARAMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <_moveit_msgs/PlannerParams.h>

namespace _moveit_msgs
{
template <class ContainerAllocator>
struct GetPlannerParamsResponse_
{
  typedef GetPlannerParamsResponse_<ContainerAllocator> Type;

  GetPlannerParamsResponse_()
    : params()  {
    }
  GetPlannerParamsResponse_(const ContainerAllocator& _alloc)
    : params(_alloc)  {
  (void)_alloc;
    }



   typedef  ::_moveit_msgs::PlannerParams_<ContainerAllocator>  _params_type;
  _params_type params;





  typedef std::shared_ptr< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPlannerParamsResponse_

typedef ::_moveit_msgs::GetPlannerParamsResponse_<std::allocator<void> > GetPlannerParamsResponse;

typedef std::shared_ptr< ::_moveit_msgs::GetPlannerParamsResponse > GetPlannerParamsResponsePtr;
typedef std::shared_ptr< ::_moveit_msgs::GetPlannerParamsResponse const> GetPlannerParamsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator1> & lhs, const ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.params == rhs.params;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator1> & lhs, const ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace _moveit_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "462b1bd59976ece800f6a48f2b0bf1a2";
  }

  static const char* value(const ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x462b1bd59976ece8ULL;
  static const uint64_t static_value2 = 0x00f6a48f2b0bf1a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "_moveit_msgs/GetPlannerParamsResponse";
  }

  static const char* value(const ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# parameters as key-value pairs\n"
"PlannerParams params\n"
"\n"
"\n"
"================================================================================\n"
"MSG: _moveit_msgs/PlannerParams\n"
"# parameter names (same size as values)\n"
"string[] keys\n"
"\n"
"# parameter values (same size as keys)\n"
"string[] values\n"
"\n"
"# parameter description (can be empty)\n"
"string[] descriptions\n"
;
  }

  static const char* value(const ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPlannerParamsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::_moveit_msgs::GetPlannerParamsResponse_<ContainerAllocator>& v)
  {
    s << indent << "params: ";
    s << std::endl;
    Printer< ::_moveit_msgs::PlannerParams_<ContainerAllocator> >::stream(s, indent + "  ", v.params);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_GETPLANNERPARAMSRESPONSE_H
