// Generated by gencpp from file _moveit_msgs/GetRobotStateFromWarehouse.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_GETROBOTSTATEFROMWAREHOUSE_H
#define _MOVEIT_MSGS_MESSAGE_GETROBOTSTATEFROMWAREHOUSE_H

#include <ros/service_traits.h>


#include <_moveit_msgs/GetRobotStateFromWarehouseRequest.h>
#include <_moveit_msgs/GetRobotStateFromWarehouseResponse.h>


namespace _moveit_msgs
{

struct GetRobotStateFromWarehouse
{

typedef GetRobotStateFromWarehouseRequest Request;
typedef GetRobotStateFromWarehouseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotStateFromWarehouse
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::GetRobotStateFromWarehouse > {
  static const char* value()
  {
    return "5daf0b8853a0f1d96bf6cfb173c42a3d";
  }

  static const char* value(const ::_moveit_msgs::GetRobotStateFromWarehouse&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::GetRobotStateFromWarehouse > {
  static const char* value()
  {
    return "_moveit_msgs/GetRobotStateFromWarehouse";
  }

  static const char* value(const ::_moveit_msgs::GetRobotStateFromWarehouse&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::GetRobotStateFromWarehouseRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetRobotStateFromWarehouse >
template<>
struct MD5Sum< ::_moveit_msgs::GetRobotStateFromWarehouseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetRobotStateFromWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::GetRobotStateFromWarehouseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetRobotStateFromWarehouseRequest> should match
// service_traits::DataType< ::_moveit_msgs::GetRobotStateFromWarehouse >
template<>
struct DataType< ::_moveit_msgs::GetRobotStateFromWarehouseRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetRobotStateFromWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::GetRobotStateFromWarehouseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::GetRobotStateFromWarehouseResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetRobotStateFromWarehouse >
template<>
struct MD5Sum< ::_moveit_msgs::GetRobotStateFromWarehouseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetRobotStateFromWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::GetRobotStateFromWarehouseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetRobotStateFromWarehouseResponse> should match
// service_traits::DataType< ::_moveit_msgs::GetRobotStateFromWarehouse >
template<>
struct DataType< ::_moveit_msgs::GetRobotStateFromWarehouseResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetRobotStateFromWarehouse >::value();
  }
  static const char* value(const ::_moveit_msgs::GetRobotStateFromWarehouseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_GETROBOTSTATEFROMWAREHOUSE_H
