// Generated by gencpp from file _moveit_msgs/GetStateValidity.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_GETSTATEVALIDITY_H
#define _MOVEIT_MSGS_MESSAGE_GETSTATEVALIDITY_H

#include <ros/service_traits.h>


#include <_moveit_msgs/GetStateValidityRequest.h>
#include <_moveit_msgs/GetStateValidityResponse.h>


namespace _moveit_msgs
{

struct GetStateValidity
{

typedef GetStateValidityRequest Request;
typedef GetStateValidityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStateValidity
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::GetStateValidity > {
  static const char* value()
  {
    return "06ea62db671e4dbf878eaca241db51ad";
  }

  static const char* value(const ::_moveit_msgs::GetStateValidity&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::GetStateValidity > {
  static const char* value()
  {
    return "_moveit_msgs/GetStateValidity";
  }

  static const char* value(const ::_moveit_msgs::GetStateValidity&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::GetStateValidityRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetStateValidity >
template<>
struct MD5Sum< ::_moveit_msgs::GetStateValidityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetStateValidity >::value();
  }
  static const char* value(const ::_moveit_msgs::GetStateValidityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetStateValidityRequest> should match
// service_traits::DataType< ::_moveit_msgs::GetStateValidity >
template<>
struct DataType< ::_moveit_msgs::GetStateValidityRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetStateValidity >::value();
  }
  static const char* value(const ::_moveit_msgs::GetStateValidityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::GetStateValidityResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::GetStateValidity >
template<>
struct MD5Sum< ::_moveit_msgs::GetStateValidityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::GetStateValidity >::value();
  }
  static const char* value(const ::_moveit_msgs::GetStateValidityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::GetStateValidityResponse> should match
// service_traits::DataType< ::_moveit_msgs::GetStateValidity >
template<>
struct DataType< ::_moveit_msgs::GetStateValidityResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::GetStateValidity >::value();
  }
  static const char* value(const ::_moveit_msgs::GetStateValidityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_GETSTATEVALIDITY_H
