// Generated by gencpp from file _moveit_msgs/LoadMap.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_LOADMAP_H
#define _MOVEIT_MSGS_MESSAGE_LOADMAP_H

#include <ros/service_traits.h>


#include <_moveit_msgs/LoadMapRequest.h>
#include <_moveit_msgs/LoadMapResponse.h>


namespace _moveit_msgs
{

struct LoadMap
{

typedef LoadMapRequest Request;
typedef LoadMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadMap
} // namespace _moveit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_moveit_msgs::LoadMap > {
  static const char* value()
  {
    return "93a4bc4c60dc17e2a69e3fcaaa25d69d";
  }

  static const char* value(const ::_moveit_msgs::LoadMap&) { return value(); }
};

template<>
struct DataType< ::_moveit_msgs::LoadMap > {
  static const char* value()
  {
    return "_moveit_msgs/LoadMap";
  }

  static const char* value(const ::_moveit_msgs::LoadMap&) { return value(); }
};


// service_traits::MD5Sum< ::_moveit_msgs::LoadMapRequest> should match
// service_traits::MD5Sum< ::_moveit_msgs::LoadMap >
template<>
struct MD5Sum< ::_moveit_msgs::LoadMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::LoadMap >::value();
  }
  static const char* value(const ::_moveit_msgs::LoadMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::LoadMapRequest> should match
// service_traits::DataType< ::_moveit_msgs::LoadMap >
template<>
struct DataType< ::_moveit_msgs::LoadMapRequest>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::LoadMap >::value();
  }
  static const char* value(const ::_moveit_msgs::LoadMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_moveit_msgs::LoadMapResponse> should match
// service_traits::MD5Sum< ::_moveit_msgs::LoadMap >
template<>
struct MD5Sum< ::_moveit_msgs::LoadMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_moveit_msgs::LoadMap >::value();
  }
  static const char* value(const ::_moveit_msgs::LoadMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_moveit_msgs::LoadMapResponse> should match
// service_traits::DataType< ::_moveit_msgs::LoadMap >
template<>
struct DataType< ::_moveit_msgs::LoadMapResponse>
{
  static const char* value()
  {
    return DataType< ::_moveit_msgs::LoadMap >::value();
  }
  static const char* value(const ::_moveit_msgs::LoadMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_LOADMAP_H
