// Generated by gencpp from file _moveit_msgs/SetPlannerParamsResponse.msg
// DO NOT EDIT!


#ifndef _MOVEIT_MSGS_MESSAGE_SETPLANNERPARAMSRESPONSE_H
#define _MOVEIT_MSGS_MESSAGE_SETPLANNERPARAMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace _moveit_msgs
{
template <class ContainerAllocator>
struct SetPlannerParamsResponse_
{
  typedef SetPlannerParamsResponse_<ContainerAllocator> Type;

  SetPlannerParamsResponse_()
    {
    }
  SetPlannerParamsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef std::shared_ptr< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetPlannerParamsResponse_

typedef ::_moveit_msgs::SetPlannerParamsResponse_<std::allocator<void> > SetPlannerParamsResponse;

typedef std::shared_ptr< ::_moveit_msgs::SetPlannerParamsResponse > SetPlannerParamsResponsePtr;
typedef std::shared_ptr< ::_moveit_msgs::SetPlannerParamsResponse const> SetPlannerParamsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace _moveit_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "_moveit_msgs/SetPlannerParamsResponse";
  }

  static const char* value(const ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPlannerParamsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::_moveit_msgs::SetPlannerParamsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOVEIT_MSGS_MESSAGE_SETPLANNERPARAMSRESPONSE_H
