// Generated by gencpp from file _std_srvs/Empty.msg
// DO NOT EDIT!


#ifndef _STD_SRVS_MESSAGE_EMPTY_H
#define _STD_SRVS_MESSAGE_EMPTY_H

#include <ros/service_traits.h>


#include <_std_srvs/EmptyRequest.h>
#include <_std_srvs/EmptyResponse.h>


namespace _std_srvs
{

struct Empty
{

typedef EmptyRequest Request;
typedef EmptyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Empty
} // namespace _std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_std_srvs::Empty > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::_std_srvs::Empty&) { return value(); }
};

template<>
struct DataType< ::_std_srvs::Empty > {
  static const char* value()
  {
    return "_std_srvs/Empty";
  }

  static const char* value(const ::_std_srvs::Empty&) { return value(); }
};


// service_traits::MD5Sum< ::_std_srvs::EmptyRequest> should match
// service_traits::MD5Sum< ::_std_srvs::Empty >
template<>
struct MD5Sum< ::_std_srvs::EmptyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_std_srvs::Empty >::value();
  }
  static const char* value(const ::_std_srvs::EmptyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_std_srvs::EmptyRequest> should match
// service_traits::DataType< ::_std_srvs::Empty >
template<>
struct DataType< ::_std_srvs::EmptyRequest>
{
  static const char* value()
  {
    return DataType< ::_std_srvs::Empty >::value();
  }
  static const char* value(const ::_std_srvs::EmptyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_std_srvs::EmptyResponse> should match
// service_traits::MD5Sum< ::_std_srvs::Empty >
template<>
struct MD5Sum< ::_std_srvs::EmptyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_std_srvs::Empty >::value();
  }
  static const char* value(const ::_std_srvs::EmptyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_std_srvs::EmptyResponse> should match
// service_traits::DataType< ::_std_srvs::Empty >
template<>
struct DataType< ::_std_srvs::EmptyResponse>
{
  static const char* value()
  {
    return DataType< ::_std_srvs::Empty >::value();
  }
  static const char* value(const ::_std_srvs::EmptyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_EMPTY_H
