// Generated by gencpp from file _std_srvs/SetBool.msg
// DO NOT EDIT!


#ifndef _STD_SRVS_MESSAGE_SETBOOL_H
#define _STD_SRVS_MESSAGE_SETBOOL_H

#include <ros/service_traits.h>


#include <_std_srvs/SetBoolRequest.h>
#include <_std_srvs/SetBoolResponse.h>


namespace _std_srvs
{

struct SetBool
{

typedef SetBoolRequest Request;
typedef SetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBool
} // namespace _std_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_std_srvs::SetBool > {
  static const char* value()
  {
    return "09fb03525b03e7ea1fd3992bafd87e16";
  }

  static const char* value(const ::_std_srvs::SetBool&) { return value(); }
};

template<>
struct DataType< ::_std_srvs::SetBool > {
  static const char* value()
  {
    return "_std_srvs/SetBool";
  }

  static const char* value(const ::_std_srvs::SetBool&) { return value(); }
};


// service_traits::MD5Sum< ::_std_srvs::SetBoolRequest> should match
// service_traits::MD5Sum< ::_std_srvs::SetBool >
template<>
struct MD5Sum< ::_std_srvs::SetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_std_srvs::SetBool >::value();
  }
  static const char* value(const ::_std_srvs::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_std_srvs::SetBoolRequest> should match
// service_traits::DataType< ::_std_srvs::SetBool >
template<>
struct DataType< ::_std_srvs::SetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::_std_srvs::SetBool >::value();
  }
  static const char* value(const ::_std_srvs::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_std_srvs::SetBoolResponse> should match
// service_traits::MD5Sum< ::_std_srvs::SetBool >
template<>
struct MD5Sum< ::_std_srvs::SetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_std_srvs::SetBool >::value();
  }
  static const char* value(const ::_std_srvs::SetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_std_srvs::SetBoolResponse> should match
// service_traits::DataType< ::_std_srvs::SetBool >
template<>
struct DataType< ::_std_srvs::SetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::_std_srvs::SetBool >::value();
  }
  static const char* value(const ::_std_srvs::SetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STD_SRVS_MESSAGE_SETBOOL_H
