controller_list:
  - name: fake_manipulator_controller
    type: interpolate
    joints:
      - elbow_joint
      - shoulder_lift_joint
      - shoulder_pan_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: all-zeros
