// Generated by gencpp from file _tf2_msgs/FrameGraphRequest.msg
// DO NOT EDIT!


#ifndef _TF2_MSGS_MESSAGE_FRAMEGRAPHREQUEST_H
#define _TF2_MSGS_MESSAGE_FRAMEGRAPHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace _tf2_msgs
{
template <class ContainerAllocator>
struct FrameGraphRequest_
{
  typedef FrameGraphRequest_<ContainerAllocator> Type;

  FrameGraphRequest_()
    {
    }
  FrameGraphRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef std::shared_ptr< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FrameGraphRequest_

typedef ::_tf2_msgs::FrameGraphRequest_<std::allocator<void> > FrameGraphRequest;

typedef std::shared_ptr< ::_tf2_msgs::FrameGraphRequest > FrameGraphRequestPtr;
typedef std::shared_ptr< ::_tf2_msgs::FrameGraphRequest const> FrameGraphRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace _tf2_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "_tf2_msgs/FrameGraphRequest";
  }

  static const char* value(const ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FrameGraphRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::_tf2_msgs::FrameGraphRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TF2_MSGS_MESSAGE_FRAMEGRAPHREQUEST_H
