// Generated by gencpp from file _control_msgs/FollowJointTrajectoryActionFeedback.msg
// DO NOT EDIT!


#ifndef _CONTROL_MSGS_MESSAGE_FOLLOWJOINTTRAJECTORYACTIONFEEDBACK_H
#define _CONTROL_MSGS_MESSAGE_FOLLOWJOINTTRAJECTORYACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <_std_msgs/Header.h>
#include <_actionlib_msgs/GoalStatus.h>
#include <_control_msgs/FollowJointTrajectoryFeedback.h>

namespace _control_msgs
{
template <class ContainerAllocator>
struct FollowJointTrajectoryActionFeedback_
{
  typedef FollowJointTrajectoryActionFeedback_<ContainerAllocator> Type;

  FollowJointTrajectoryActionFeedback_()
    : header()
    , status()
    , feedback()  {
    }
  FollowJointTrajectoryActionFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(_alloc)
    , feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::_std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::_actionlib_msgs::GoalStatus_<ContainerAllocator>  _status_type;
  _status_type status;

   typedef  ::_control_msgs::FollowJointTrajectoryFeedback_<ContainerAllocator>  _feedback_type;
  _feedback_type feedback;





  typedef std::shared_ptr< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FollowJointTrajectoryActionFeedback_

typedef ::_control_msgs::FollowJointTrajectoryActionFeedback_<std::allocator<void> > FollowJointTrajectoryActionFeedback;

typedef std::shared_ptr< ::_control_msgs::FollowJointTrajectoryActionFeedback > FollowJointTrajectoryActionFeedbackPtr;
typedef std::shared_ptr< ::_control_msgs::FollowJointTrajectoryActionFeedback const> FollowJointTrajectoryActionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator1> & lhs, const ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status &&
    lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator1> & lhs, const ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace _control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8920dc4eae9fc107e00999cce4be641";
  }

  static const char* value(const ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8920dc4eae9fc10ULL;
  static const uint64_t static_value2 = 0x7e00999cce4be641ULL;
};

template<class ContainerAllocator>
struct DataType< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "_control_msgs/FollowJointTrajectoryActionFeedback";
  }

  static const char* value(const ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"_actionlib_msgs/GoalStatus status\n"
"FollowJointTrajectoryFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: _std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: _actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: _actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: _control_msgs/FollowJointTrajectoryFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"Header header\n"
"string[] joint_names\n"
"_trajectory_msgs/JointTrajectoryPoint desired\n"
"_trajectory_msgs/JointTrajectoryPoint actual\n"
"_trajectory_msgs/JointTrajectoryPoint error\n"
"\n"
"\n"
"================================================================================\n"
"MSG: _trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowJointTrajectoryActionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::_control_msgs::FollowJointTrajectoryActionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::_std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::_actionlib_msgs::GoalStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
    s << indent << "feedback: ";
    s << std::endl;
    Printer< ::_control_msgs::FollowJointTrajectoryFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_FOLLOWJOINTTRAJECTORYACTIONFEEDBACK_H
