// Generated by gencpp from file _sensor_msgs/SetCameraInfo.msg
// DO NOT EDIT!


#ifndef _SENSOR_MSGS_MESSAGE_SETCAMERAINFO_H
#define _SENSOR_MSGS_MESSAGE_SETCAMERAINFO_H

#include <ros/service_traits.h>


#include <_sensor_msgs/SetCameraInfoRequest.h>
#include <_sensor_msgs/SetCameraInfoResponse.h>


namespace _sensor_msgs
{

struct SetCameraInfo
{

typedef SetCameraInfoRequest Request;
typedef SetCameraInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCameraInfo
} // namespace _sensor_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::_sensor_msgs::SetCameraInfo > {
  static const char* value()
  {
    return "bef1df590ed75ed1f393692395e15482";
  }

  static const char* value(const ::_sensor_msgs::SetCameraInfo&) { return value(); }
};

template<>
struct DataType< ::_sensor_msgs::SetCameraInfo > {
  static const char* value()
  {
    return "_sensor_msgs/SetCameraInfo";
  }

  static const char* value(const ::_sensor_msgs::SetCameraInfo&) { return value(); }
};


// service_traits::MD5Sum< ::_sensor_msgs::SetCameraInfoRequest> should match
// service_traits::MD5Sum< ::_sensor_msgs::SetCameraInfo >
template<>
struct MD5Sum< ::_sensor_msgs::SetCameraInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::_sensor_msgs::SetCameraInfo >::value();
  }
  static const char* value(const ::_sensor_msgs::SetCameraInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::_sensor_msgs::SetCameraInfoRequest> should match
// service_traits::DataType< ::_sensor_msgs::SetCameraInfo >
template<>
struct DataType< ::_sensor_msgs::SetCameraInfoRequest>
{
  static const char* value()
  {
    return DataType< ::_sensor_msgs::SetCameraInfo >::value();
  }
  static const char* value(const ::_sensor_msgs::SetCameraInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::_sensor_msgs::SetCameraInfoResponse> should match
// service_traits::MD5Sum< ::_sensor_msgs::SetCameraInfo >
template<>
struct MD5Sum< ::_sensor_msgs::SetCameraInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::_sensor_msgs::SetCameraInfo >::value();
  }
  static const char* value(const ::_sensor_msgs::SetCameraInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::_sensor_msgs::SetCameraInfoResponse> should match
// service_traits::DataType< ::_sensor_msgs::SetCameraInfo >
template<>
struct DataType< ::_sensor_msgs::SetCameraInfoResponse>
{
  static const char* value()
  {
    return DataType< ::_sensor_msgs::SetCameraInfo >::value();
  }
  static const char* value(const ::_sensor_msgs::SetCameraInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_MSGS_MESSAGE_SETCAMERAINFO_H
